#Data source

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:TecJTzcUb1qjKaYzrTR9@containers-us-west-64.railway.app:6548/railway
    username: containers-us-west-64.railway.app
    password: TecJTzcUb1qjKaYzrTR9
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: emailserver898@gmail.com
    password: HfSaPUN36bpTkVwL
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true



twilio:
  account:
    sid: AC7ae6cad8513316f6c5b1a29bc1594855
  auth:
    token: 3cf921617b43f475fdd046179d93749e
  phone:
    number: +16188511542



